# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CraftMyStreet
                                 A QGIS plugin
 CraftMyStreet
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-01-03
        copyright            : (C) 2024 by UCD
        email                : craftmystreet@ucd.ie
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CraftMyStreet class from file CraftMyStreet.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .craft_my_street import CraftMyStreet
    return CraftMyStreet(iface)
